### ISSUE TITLE
Configure travis to run `osx` environment

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware-contrib/ng2-json-editor#153]
We must configure travis to run all tests in `osx` environment too. Every attemp ended up to this error:
```
24 01 2017 13:17:21.758:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
24 01 2017 13:17:21.762:INFO [launcher]: Launching browser Chrome_travis_ci with unlimited concurrency
24 01 2017 13:17:21.774:INFO [launcher]: Starting browser Chrome
24 01 2017 13:19:01.780:WARN [launcher]: Chrome have not captured in 100000 ms, killing.
24 01 2017 13:19:03.785:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.
24 01 2017 13:19:05.787:WARN [launcher]: Chrome was not killed by SIGKILL in 2000 ms, continuing.
```

Issue maybe related with karma and osx environment.

Maybe related issue with this one : 
https://github.com/karma-runner/karma/issues/635

Latest travis.yml effort:
```
os:
  - osx
notifications:
  email: false
language: node_js
node_js:
  - '6.9.1'
  - node
sudo: true
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache: yarn
env:
  global:
    - GH_REF: 'github.com/inveniosoftware-contrib/ng2-json-editor.git'
    - secure: "sdfkNpOtiUBxJ8aMAFjXbs9ewl8L/UWNipZGuIdgZjuWKuzxUTJd8efohQUPND0cNr+JMwSzZ5jw4gv98MuzigyUKHtMW7YhHfIJ5M9/epyE6qD8jyeaIFGAfZQ4zFkJAnR88U70MT3ca4PuvrNUTh1bDd4VS1QLQlfuHdCuaOHZk7+oemWXutsZdX2lllCns72MP9t2WO3OQVUDzCTq+96nia6h6LCq4kuRIr3T7T98WoYD16zArk/HG6j9D3wiuWm79D75q0yYCh7cfkSG9goytk87R0alVVXQ0+muyNMsQgUUe8Z39xOVnhen78F46FieQX2/03ukOmxOqYzTXwa3y3EP0ei2al99f829cip/Ag/52nE1BJAG6oIUYGykfyHdgPl6J17anZWHwu2FF5wNn7KpodWKz13nf+Y6C8sGdnYGRBNDnh10L+85fJKDNzYXgDK225zgbMAKBko9zof6rnFDEz9I/4f9FMEe1pKSzN4lrnT1THD05h43YQeFhbC0wH9q9cityD3Kpf04lxftbFhTi7jzLrhKiqitpopf9S8pKeVrTRQn4fdXg2xmwqlB+RaDquzkw7ur1xXcXdDIPkmCURSTVgHczfmC5cRCNHBIQQPN/CflFT9yhif3b/MLrwKmygy/6ms7Lp7yX4//4MMV237/NL4oIgLCXVw="
before_install:
  - sudo bash -c 'echo "127.0.0.1 localhost" > /etc/hosts'
  - sudo bash -c 'echo "255.255.255.255 broadcasthost" >> /etc/hosts'
  - sudo bash -c 'echo "::1 localhost" >> /etc/hosts'
  - cat /etc/hosts
  - npm install buffer-shims
  - export CHROME_BIN=chromium-browser
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - mkdir /tmp/.X11-unix
  - sudo chmod 1777 /tmp/.X11-unix
  - sudo chown root /tmp/.X11-unix
  - export DISPLAY=:99.0
  - /usr/X11/bin/Xvfb :99.0 &
before_deploy: npm run build
after_success:
  - npm run coveralls
deploy:
  provider: npm
  skip_cleanup: true
  email: admin@inspirehep.net
  api_key:
    secure: ZO0gp0WoyzYY6/UBbwJVIH8Dt0Vay2Dvc/Lb1XmcfwbVMNk5VIDUvo4EUSXR0DBTh+h6A3in8oLmIKBcir2nSnUT6+ATzkT5K5dyZKloZ47uYDsgsFnnLbyqn7iDjljl0/NSBFwXoNr6IiLHEWU/9Qv1Qyim1bQDoL5xK7d2u4jDxXk932fSAySn2foq6235WH8UK2ACekzffCoHmfmjRpYrs/OIGLAvuMKt31gW9/bzu61oLaI8bHuoxAQjc7CN57qlUh7Ffmr6tABcVwuFMm5EVaEosZsdJAR6guVrcAch1rE6gHCqZLGUrrPdOh9925xbtN3VeLWXrB9Z3FdubicARf1Q+A62+9XGDzIKSwTLpG9nyIfeFj1QEljNmIpXHp+wmMDEaZjM6bSf72B/kXhhb5G6bLc0XOt1yqXhM8ytnYUQGBlTDqKz1SnNL7bSEE20AncAueVFarJ7mB34BXQ6qAhZXGmfAVkWClr4RyMtVzSy0rhRBynVF3+vM3owpxD/cDffQQ3M7ehszzRXsnIsAZAoErvciQEv4DH/J+AWXy7s3JuxYflvjj2hPLlMvVqM9XFn9Y/SZiBtNIqKfIM17srU+vBSPclxEarWodj4n5WPmMGT09GFNxsbbHL51rv27Hf6U37BQviMYDqmWexoJ56+ohnSyZ+t28IRol0=
  on:
    tags: true
    repo: inveniosoftware-contrib/ng2-json-editor
    all_branches: true
    node: '6.9.1'
after_deploy:
  - ./deploy-gh-pages.sh

```

Tried to set etc/hosts because it was found to be this one:
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
255.255.255.255	broadcasthost
::1             localhost
127.0.0.1 localhost 127.0.0.1	localhost 
```
and transformed to this one:
```
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
```
but it didn't work. We must investigate it further.
